service:
  flush: 1
  log_level: info
  http_server: on
  storage.metrics: on
  health_check: on
pipeline:
  inputs:
    - name: systemd
      alias: input_systemd_k8s
      tag: host.*
      systemd_filter: _SYSTEMD_UNIT=kubelet.service
      read_from_tail: true
      lowercase: on
      threaded: true
  outputs:
      - name: stdout
        alias: output_stdout_all
        match: "*"
