name: Reusable workflow to run container tests
on:
  workflow_call:
    inputs:
      ref:
        description: The commit, SHA or branch to use in this repository.
        required: false
        type: string
        default: main
      image:
        description: The full image name to test.
        required: false
        default: "ghcr.io/fluentdo/agent"
        type: string
      image-tag:
        description: The image tag to test.
        required: true
        type: string
    secrets:
      github-token:
        description: Token to use to pull images from GitHub Container Registry.
        required: true
jobs:

  get-meta:
    name: Get meta information required
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      kind-versions: ${{ steps.set-meta.outputs.kind-versions }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          repository: FluentDo/agent
          ref: ${{ inputs.ref || github.ref }}

      - name: Extract the configuration from the JSON file
        id: set-meta
        run: |
          KIND_VERSIONS=$(cat "$JSON_FILE_NAME" | jq -c .kind_versions )
          echo "kind-versions=$KIND_VERSIONS"
          echo "kind-versions=$KIND_VERSIONS" >> $GITHUB_OUTPUT
        shell: bash
        env:
          JSON_FILE_NAME: build-config.json

  test-container-config:
    name: Test config of ${{ inputs.image }}:${{ inputs.image-tag }}
    runs-on: ubuntu-latest
    env:
      IMAGE: ${{ inputs.image }}
      IMAGE_TAG: ${{ inputs.image-tag }}
    permissions:
      packages: read
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          repository: FluentDo/agent
          ref: ${{ inputs.ref || github.ref }}
          token: ${{ secrets.github-token }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.github-token }}

      - name: Run config tests
        run: ./testing/verify-config.sh
        shell: bash

  test-redhat-certification:
    name: Test UBI container will pass certification
    if: contains( inputs.image, 'ubi' )
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.github-token }}

      - name: Set up preflight binary
        run: |
          curl -sSfLO https://github.com/redhat-openshift-ecosystem/openshift-preflight/releases/download/1.14.1/preflight-linux-amd64
          chmod a+x ./preflight-linux-amd64
        shell: bash

      - name: Run tests
        run: ./preflight-linux-amd64 check container ${{ inputs.image }}:${{ inputs.image-tag }}
        shell: bash

      - name: Preflight log
        continue-on-error: true
        run: cat preflight.log
        shell: bash

      - name: Image debug
        continue-on-error: true
        run: docker inspect ${{ inputs.image }}:${{ inputs.image-tag }}
        shell: bash

  test-kubernetes:
    name: Run container tests for ${{ inputs.image }}:${{ inputs.image-tag }} on K8S version ${{ matrix.kind-version }}
    uses: ./.github/workflows/call-test-containers-k8s.yaml
    needs:
      - get-meta
    with:
      kind-version: ${{ matrix.kind-version }}
      image: ${{ inputs.image }}
      image-tag: ${{ inputs.image-tag }}
      ref: ${{ inputs.ref }}
    secrets:
      github-token: ${{ secrets.github-token }}
    strategy:
      matrix:
        kind-version: ${{ fromJson(needs.get-meta.outputs.kind-versions) }}

  test-complete:
    name: All container tests complete
    runs-on: ubuntu-latest
    needs:
      - test-kubernetes
      - test-container-config
    steps:
      - name: All tests passed
        run: echo "All tests passed for ${{ inputs.image }}:${{ inputs.image-tag }}"
        shell: bash
