name: Run tests for specific versions
on:
  workflow_dispatch:
    inputs:
      image:
        description: The full image name to test.
        required: false
        default: "ghcr.io/fluentdo/agent"
        type: string
      image-tag:
        description: The image tag to test.
        required: true
        type: string
      ref:
        description: The commit, SHA or branch to use in this repository.
        required: false
        type: string
        default: main
jobs:
  get-meta:
    name: Get meta information required
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      kind-versions: ${{ steps.set-meta.outputs.kind-versions }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          repository: FluentDo/agent
          ref: ${{ github.event.inputs.ref || github.ref }}
      - name: Extract the configuration from the JSON file
        id: set-meta
        run: |
          KIND_VERSIONS=$(cat "$JSON_FILE_NAME"|jq -c .kind_versions )
          echo "kind-versions=$KIND_VERSIONS"
          echo "kind-versions=$KIND_VERSIONS" >> $GITHUB_OUTPUT
        shell: bash
        env:
          JSON_FILE_NAME: build-config.json

  test-containers:
    name: Run container tests
    uses: ./.github/workflows/call-test-containers.yaml
    needs:
      - get-meta
    with:
      image: ${{ github.event.inputs.image }}
      image-tag: ${{ github.event.inputs.image-tag }}
      ref: ${{ github.event.inputs.ref }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
